### ISSUE TITLE
师傅考虑加个body模块吗

### ISSUE THREAD

**Issue by f0ng** [MaskCyberSecurityTeam/BurpHeaderHelper#1]
感觉header、cookie这两个模块少一个body模块

**Comment by Richard-Tang** [comment]
> 感觉header、cookie这两个模块少一个body模块

行的，有空增加一下。

**Comment by Richard-Tang** [comment]
已新增HttpBody替换
https://github.com/MaskCyberSecurityTeam/BurpHttpHelper/releases/tag/1.3.1
