### ISSUE TITLE
师傅考虑下加个内容替换功能不

### ISSUE THREAD

**Issue by starscow** [MaskCyberSecurityTeam/BurpHeaderHelper#2]
师傅考虑下加个内容替换功能不

**Comment by Richard-Tang** [comment]
> 师傅考虑下加个内容替换功能不

行的，有空增加一下。

**Comment by Richard-Tang** [comment]
已新增HttpBody替换
https://github.com/MaskCyberSecurityTeam/BurpHttpHelper/releases/tag/1.3.1
