### ISSUE TITLE
师傅请教一下,我这边没成功添加和删除header头

### ISSUE THREAD

**Issue by lanqingaa** [MaskCyberSecurityTeam/BurpHeaderHelper#4]
代理模块抓包没有添加xff头,也没删除Cache-Control头
<img width="602" alt="1678273786591" src="https://user-images.githubusercontent.com/94030940/223697060-1cebe535-595a-4fb3-a52e-348d81972fda.png">
<img width="810" alt="1678273824495" src="https://user-images.githubusercontent.com/94030940/223697167-820907bc-000c-4e83-8810-c180bf182c26.png">

**Comment by JDXN** [comment]
我也是，请师傅指导一下
